DROP SEQUENCE "SEQ_EITS_ARTICLE";
DROP SEQUENCE "SEQ_EITS_ARTICLELOG";
DROP SEQUENCE "SEQ_EITS_ATTACHMENT";
DROP SEQUENCE "SEQ_EITS_STATIS";

CREATE SEQUENCE "SEQ_EITS_ARTICLE" INCREMENT BY 1 START WITH 100;
CREATE SEQUENCE "SEQ_EITS_ARTICLELOG" INCREMENT BY 1 START WITH 100;
CREATE SEQUENCE "SEQ_EITS_ATTACHMENT" INCREMENT BY 1 START WITH 100;
CREATE SEQUENCE "SEQ_EITS_STATIS" INCREMENT BY 1 START WITH 100;
CREATE SEQUENCE "SEQ_ARTICLE_ID" INCREMENT BY 1 START WITH 200;

CREATE TABLE "T_EITS_ARTICLE" (   
	"OID" NUMBER(19,0) PRIMARY KEY, 
	"CREATE_ACCOUNT" VARCHAR2(50CHAR), 
	"CREATE_DATE" TIMESTAMP(6) NULL, 
	"MODIFY_ACCOUNT" VARCHAR2(50CHAR), 
	"MODIFY_DATE" TIMESTAMP(6) NULL, 
	"AGENT_TYPE" VARCHAR2(10CHAR), 
	"ANSWER" CLOB, 
	"ENTRY_DATE" TIMESTAMP(6) NULL, 
	"ENTRY_USER" VARCHAR2(30CHAR), 
	"EXPIRE_DATE" TIMESTAMP(6) NULL, 
	"EXPIRE_TYPE" VARCHAR2(10CHAR), 
	"HITCOUNT" NUMBER(10,0), 
	"KEYWORDS" VARCHAR2(100CHAR), 
	"LEVEL_TYPE" VARCHAR2(10CHAR), 
	"NEWS" CHAR(1CHAR), 
	"PROBLEM" VARCHAR2(100CHAR), 
	"PROCEDURE_DATA" VARCHAR2(100CHAR), 
	"PRODUCT" VARCHAR2(100CHAR), 
	"PROJECT_CODE" VARCHAR2(100CHAR), 
	"PUBLISH_DATE" TIMESTAMP(6) NULL, 
	"QUESTION" CLOB, 
	"RATE_1" NUMBER(10,0), 
	"RATE_2" NUMBER(10,0), 
	"RATE_3" NUMBER(10,0), 
	"RATE_4" NUMBER(10,0), 
	"RATE_5" NUMBER(10,0), 
	"SCENARIO" VARCHAR2(100CHAR), 
	"SOLUTION" VARCHAR2(100CHAR), 
	"SOURCE" VARCHAR2(10CHAR), 
	"STATUS" VARCHAR2(32CHAR), 
	"STEP" VARCHAR2(100CHAR), 
	"SUMMARY" VARCHAR2(100CHAR), 
	"TECHNOLOGY" VARCHAR2(100CHAR), 
	"TICKET_ID" VARCHAR2(50CHAR), 
	"TYPE" VARCHAR2(20CHAR), 
	"UPDATE_DATE" TIMESTAMP(6) NULL, 
	"USER_GROUP" VARCHAR2(20CHAR), 
	"VERIFICATION" VARCHAR2(100CHAR), 
	"ARTICLEID_OID" VARCHAR2(32CHAR), 
	"FIRMWARE_OID" NUMBER(19,0), 
	"LANGUAGE_OID" VARCHAR2(32CHAR)
);

CREATE TABLE "T_EITS_ATTACHMENT" (   
	"OID" NUMBER(19,0) PRIMARY KEY, 
	"CONTENT_TYPE" VARCHAR2(50CHAR), 
	"EXTENSION" VARCHAR2(10CHAR), 
	"NAME" VARCHAR2(100CHAR), 
	"REAL_ABS_PATH" VARCHAR2(400CHAR), 
	"URI" VARCHAR2(255CHAR)
);

CREATE TABLE "T_EITS_STATIS" (   
	"OID" NUMBER(19,0) PRIMARY KEY, 
	"ACCOUNT" VARCHAR2(50CHAR), 
	"ACTION" VARCHAR2(10CHAR), 
	"ARTICLE_OID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP(6), 
	"IP" VARCHAR2(40CHAR)
);

CREATE TABLE "T_EITS_ARTICLEID" (   
	"OID" VARCHAR2(32CHAR) PRIMARY KEY
);

CREATE TABLE "T_EITS_ARTICLELOG" (   
	"OID" NUMBER(19,0) PRIMARY KEY, 
	"ACCOUNT" VARCHAR2(50CHAR), 
	"ACTION" VARCHAR2(10CHAR), 
	"ARTICLE_OID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP(6), 
	"IP" VARCHAR2(40CHAR), 
	"MESSAGE" VARCHAR2(200CHAR)
);

CREATE TABLE "T_EITS_LANGUAGE" (   
	"OID" VARCHAR2(32CHAR) PRIMARY KEY, 
	"CREATE_ACCOUNT" VARCHAR2(50CHAR), 
	"CREATE_DATE" TIMESTAMP(6), 
	"MODIFY_ACCOUNT" VARCHAR2(50CHAR), 
	"MODIFY_DATE" TIMESTAMP(6), 
	"NAME" VARCHAR2(50CHAR), 
	"IS_SYSTEM" CHAR(1CHAR)
);

