CREATE SEQUENCE "SEQ_EITS_EXPORT_PACKAGE" INCREMENT BY 1 START WITH 1;
alter table T_EITS_ARTICLE add EXPORTPACKAGE_OID VARCHAR2(32CHAR);
CREATE TABLE "T_EITS_EXPORT_PACKAGE" (   
	"OID" VARCHAR2(32CHAR)  PRIMARY KEY, 
	"CREATE_ACCOUNT" VARCHAR2(50CHAR), 
	"CREATE_DATE" TIMESTAMP(6) NULL, 
	"MODIFY_ACCOUNT" VARCHAR2(50CHAR), 
	"MODIFY_DATE" TIMESTAMP(6) NULL, 
	"ARTICLE_TYPES" VARCHAR2(100CHAR),
	"ARTICLE_ID_LIST" VARCHAR2(500CHAR), 
	"BEGIN_DATE" TIMESTAMP(6) NULL, 
	"CLOSED" CHAR(3CHAR), 
	"END_DATE" TIMESTAMP(6) NULL, 
	"EXPORT_DATE" TIMESTAMP(6) NULL, 
	"NEWS" CHAR(3CHAR)
);
