CREATE SEQUENCE SEQ_EITS_ARTICLELOG START WITH 1;
CREATE SEQUENCE SEQ_EITS_ATTACHMENT START WITH 1;
CREATE SEQUENCE SEQ_EITS_ARTICLE START WITH 1;
CREATE SEQUENCE SEQ_EITS_STATIS START WITH 1;
CREATE TABLE T_EITS_ARTICLE(
    OID BIGINT NOT NULL,
    CREATE_ACCOUNT VARCHAR(50),
    CREATE_DATE TIMESTAMP,
    MODIFY_ACCOUNT VARCHAR(50),
    MODIFY_DATE TIMESTAMP,
    AGENT_TYPE VARCHAR(10),
    ANSWER CLOB,
    ENTRY_DATE TIMESTAMP,
    ENTRY_USER VARCHAR(30),
    EXPIRE_DATE TIMESTAMP,
    EXPIRE_TYPE VARCHAR(10),
    HITCOUNT INTEGER,
    KEYWORDS VARCHAR(100),
    LEVEL_TYPE VARCHAR(10),
    NEWS CHAR(3),
    PROBLEM VARCHAR(100),
    PROCEDURE_DATA VARCHAR(100),
    PRODUCT VARCHAR(100),
    PROJECT_CODE VARCHAR(20),
    PUBLISH_DATE TIMESTAMP,
    QUESTION CLOB,
    RATE_1 INTEGER,
    RATE_2 INTEGER,
    RATE_3 INTEGER,
    RATE_4 INTEGER,
    RATE_5 INTEGER,
    SCENARIO VARCHAR(100),
    SOLUTION VARCHAR(100),
    SOURCE VARCHAR(10),
    STATUS VARCHAR(32),
    STEP VARCHAR(100),
    SUMMARY VARCHAR(100),
    TECHNOLOGY VARCHAR(100),
    TICKET_ID VARCHAR(50),
    TYPE VARCHAR(20),
    UPDATE_DATE TIMESTAMP,
    USER_GROUP VARCHAR(20),
    VERIFICATION VARCHAR(100),
    ARTICLEID_OID VARCHAR(32),
    FIRMWARE_OID BIGINT,
    LANGUAGE_OID VARCHAR(32)
);

CREATE TABLE T_EITS_ARTICLEID(
    OID VARCHAR(32) NOT NULL
);

CREATE TABLE T_EITS_ARTICLELOG(
    OID BIGINT NOT NULL,
    ACCOUNT VARCHAR(50),
    ACTION VARCHAR(10),
    ARTICLE_OID BIGINT,
    CREATE_DATE TIMESTAMP,
    IP VARCHAR(40),
    MESSAGE VARCHAR(200)
)
CREATE TABLE T_EITS_ATTACHMENT(
    OID BIGINT NOT NULL,
    CONTENT_TYPE VARCHAR(20),
    EXTENSION VARCHAR(10),
    NAME VARCHAR(100),
    REAL_ABS_PATH VARCHAR(400),
    URI VARCHAR(255)
);

CREATE TABLE T_EITS_LANGUAGE(
    OID VARCHAR(32) NOT NULL,
    CREATE_ACCOUNT VARCHAR(50),
    CREATE_DATE TIMESTAMP,
    MODIFY_ACCOUNT VARCHAR(50),
    MODIFY_DATE TIMESTAMP,
    NAME VARCHAR(50),
    IS_SYSTEM CHAR(3)
);

CREATE TABLE T_EITS_STATIS(
    OID BIGINT NOT NULL,
    ACCOUNT VARCHAR(50),
    ACTION VARCHAR(10),
    ARTICLE_OID BIGINT,
    CREATE_DATE TIMESTAMP,
    IP VARCHAR(40)
);

ALTER TABLE PUBLIC.T_EITS_LANGUAGE ADD CONSTRAINT PUBLIC.CONSTRAINT_A UNIQUE(NAME);
ALTER TABLE PUBLIC.T_EITS_ARTICLE ADD CONSTRAINT PUBLIC.FKED7B38C597A28955 FOREIGN KEY(ARTICLEID_OID) REFERENCES PUBLIC.T_EITS_ARTICLEID(OID) NOCHECK;
ALTER TABLE PUBLIC.T_EITS_ARTICLE ADD CONSTRAINT PUBLIC.FKED7B38C546360F33 FOREIGN KEY(LANGUAGE_OID) REFERENCES PUBLIC.T_EITS_LANGUAGE(OID) NOCHECK;
ALTER TABLE PUBLIC.T_EITS_ARTICLE ADD CONSTRAINT PUBLIC.FKED7B38C54A1E93E1 FOREIGN KEY(FIRMWARE_OID) REFERENCES PUBLIC.T_EITS_ATTACHMENT(OID) NOCHECK;
